### ISSUE TITLE
Setting canvas scale based on context (coordinate systems)

### ISSUE THREAD

**Issue by timholy** [dcjones/Compose.jl#134]
Now that packages load quickly, I'm back to being interested in graphics again. I thought I'd dive into Compose/Gadfly and start learning. Until I just can't stand it anymore, I'm deliberately trying to hold myself back from digging into the source code too much; this recent picture of me will show you why:
![image](https://cloud.githubusercontent.com/assets/1525481/8829881/c52c0534-305e-11e5-89cb-270b6ce27a95.png)
Naturally, I plan on submitting documentation and/or source code PRs.

Here's my first obstacle:
```jl
using Compose, Color

c = context()
colors = colormap("RdBu", 20)
for i = 1:20
    x, y = randn(), randn()
    r = rand()
    compose!(c, compose(context(), circle(x, y, r), fill(nothing), stroke(colors[i])))
end
img = SVG("/tmp/circles.png", 4inch, 4inch)
draw(img, c)
```
![circles](https://cloud.githubusercontent.com/assets/1525481/8829936/0ffa8752-305f-11e5-814e-581760b0d870.png)

It seems like it should be easy to set up the canvas to be the boundingbox of all the data in `c`.

**Comment by shashi** [comment]
> Now that packages load quickly, I'm back to being interested in graphics again.

Awesome! Just want to let you know we tried to do a little optimizing during JuliaCon: https://github.com/dcjones/Compose.jl/pull/131

I'd think starting off with
```julia
c = context(units=UnitBox(-2, -2, 4, 4))
```
would do the trick here, but it does not.

**Comment by dcjones** [comment]
There's not a way now to automatically fit the units to the data like that. Part of the difficulty is that, because compose let's you mix unit types, it's not always possible to do. Like if I said `circle(0, 0, 12inch)`, setting just coordinate system is not sufficient to ensure the circle is drawn in-bounds.

**Comment by dcjones** [comment]
Unrelated compose tip: your example can be written more conveniently (and efficiently) like:
```julia
n = 20
c = compose(context(), circle(randn(n), randn(n), rand(n)),
            fill(nothing), stroke(colormap("RdBu", n)))
```

**Comment by timholy** [comment]
Cool tip. If not in the docs, I'll immortalize it.

For the bigger issue: I guess the main point is that somewhere, values like 1.8 are getting turned into real units like `mm`. Could one mimic this transformation and then use it to set the coordinates of the canvas? Something like
```jl
img = SVG("/tmp/circles.png", 4inch, 4inch)
bb = boundingbox(img, c)  # makes the same transformations that draw would
set_coords!(img, bb)          # sets the coords of img to span the given bb
draw(img, c)
```
If this seems feasible and desirable, I could take a crack at implementing it.

**Comment by dcjones** [comment]
I do touch on the [vectorization thing](http://composejl.org/#forms-and-properties-can-be-vectorized), though not in any depth.

It is possible to compute the bounding box if you know the image size. In fact @Keno has already implemented a `boundingbox` function (which was no small feat!).

You may be underestimating how difficult the problem is in general though. I think it boils down to linear programming: there is a set of linear inequalities and you want to find the smallest width/height that satisfy those inequalities, with the caveat that it may be impossible to satisfy some. Building a solver for this would actually be really cool, it would enable some crazy layout stuff. I've thought about this before in the past: a really early design I had for compose was to allow one to introduce arbitrary units and let compose form the linear program and resolve them.

So I think solving this in general is pretty significant project, but there may be restricted version that would be easy and useful to compute.

(As an example of an infeasibility, if I say something like `circle(2w, 2h, 1w)`, it will always be drawn outside the context, regardless of the size of the image or the units.)

**Comment by timholy** [comment]
Thanks for the cautionary remarks. I'll take your sage advice.
